### ISSUE TITLE
help (not bug) with determining Player.title

### ISSUE THREAD

**Issue by jchhenderson** [iharosi/homebridge-plex-webhooks#1]
Hi,

The plugin is working :-) but I cannot get the right name for player.title

According to Plex, it is "**Plex for Apple TV - Living room**" but this does not work.  I have looked through the Plex logs but it only shows **tvOS (Living Room)** which also does not work.

I have tried using `--debug` to get the payload info, but I might be doing this wrong.  I typed `--debug` into the field at Home bridge Settings -> Debug and restarted, but all I got from the log was:
```
[6/25/2020, 9:24:07 PM] [Plex] Occupancy sensor state change has triggered: media.play
[6/25/2020, 9:24:14 PM] [Plex] Occupancy sensor state change has triggered: media.stop
```

Sorry to be a pain, but can you please tell me where I am going wrong?

cheers,
James.

**Comment by jchhenderson** [comment]
OK, so for anyone needing the same info...

Using an [online listener](https://webhook.site/#!/05f5c8f0-21e5-45a4-8652-9cc417f45a28/cdc9c61e-544e-4713-9a49-54a9ca13434b/1), I was able to determine that `Player.title` was `Living Room`, the part after the `-`.

**Comment by iharosi** [comment]
Hi @jchhenderson,

Sorry for the late response!
I'll repoen this issue as a better debug option would be helpful for this plugin.
Thanks for sharing your findings!

**Comment by jchhenderson** [comment]
thanks!
