### ISSUE TITLE
Media Paused

### ISSUE THREAD

**Issue by AviatorBimmer** [iharosi/homebridge-plex-webhooks#14]
Hello, first let me say this plugin has been a life saver!!! Thank you so much for creating and maintaining it.

I got it working but I was wondering how can I make a sensor that triggers when a media is PAUSED and and another one for STOPPED.

Any help will be greatly appreciated!

**Comment by logix-ams** [comment]
+1

**Comment by iharosi** [comment]
This is a duplication of https://github.com/iharosi/homebridge-plex-webhooks/issues/13 so, closing.
