### ISSUE TITLE
I’m struggling.

### ISSUE THREAD

**Issue by gleasonmagic79** [iharosi/homebridge-plex-webhooks#15]
I’m having trouble getting the sensor to register when Plex is playing.   

![128E06EB-4E0E-4E81-AE26-8B407ED8681E](https://user-images.githubusercontent.com/62533674/127433025-12e0478b-4501-435b-a049-818c547731e0.png)

**Comment by iharosi** [comment]
Could you please provide your JSON config instead of screenshot?
And a verbose log from Homebridge?
