### ISSUE TITLE
External Server

### ISSUE THREAD

**Issue by UrsLebowski** [iharosi/homebridge-plex-webhooks#16]
Hello, 
i use webhooks with homebridge and plexserver in the same network. that works wonderfully. now i wanted to use webhooks on a homebridge in the holiday home. I have released the plexport in the server-network and in the plugin config instead of the 192.x.x. address, the public ip or fritzbox account address entered. but the sensor does not respond. does the interaction of homebridge and plex server work in different networks at all?

LG
Urs

__________________________________________________________________________________________________________________________
Hallo, 
ich nutze webhooks mit homebridge und plexserver im selben netzwerk. das funktioniert wunderbar. jetzt wollte ich webhooks auch auf einer homebridge im ferienhaus nutzen. ich habe den plexport beim servernetzwerk freigegeben und in der plugin konfig statt die 192.x.x. adresse, die öffentliche ip, bzw. fritzbox-konto adresse eingetragen. aber der sensor reagiert nicht. funktioniert das zusammenspiel von homebridge und plex server in unterschiedlichen netztwerken überhaupt?

LG
Urs

**Comment by UrsLebowski** [comment]
the log:
17.8.2021, 18:11:16Plex Webhooks Bridge starting
17.8.2021, 18:11:20Plex Webhooks BridgeLoaded plugin 'homebridge-plex-webhooks'
17.8.2021, 18:11:20Plex Webhooks BridgeLoading 1 platforms...
17.8.2021, 18:11:20Plex Webhooks BridgePlex Webhooks PlatformFound 2 accessories in config:
17.8.2021, 18:11:20Plex Webhooks BridgePlex Webhooks Platform• Plex in der Ofenecke
17.8.2021, 18:11:20Plex Webhooks BridgePlex Webhooks Platform• Plex Spielt ab
17.8.2021, 18:11:20Plex Webhooks BridgePlex Webhooks PlatformUpdating accessory [Plex in der Ofenecke] (49b360dc-78ff-447b-987f-de34b36b45f6)
17.8.2021, 18:11:20Plex Webhooks BridgePlex Webhooks PlatformUpdating accessory [Plex Spielt ab] (4a7952eb-3ec0-41a6-b952-3704a495ca1c)
17.8.2021, 18:11:20Plex Webhooks BridgeBridge is running on port 51836.
17.8.2021, 18:11:20Plex Webhooks BridgePlex Webhooks PlatformFEHLERError: address is not available xx.xxx.xx.xxx:32400

**Comment by iharosi** [comment]
It depends on your network interfaces. The plugin itself uses the available network based on your server's network interfaces. It's something you should configure on your host (server) which runs homebridge. Nothing to do with the plugin.

**Comment by TheCableGuy99** [comment]
Sorry to open this, but i'm having the same issue. I am getting the error:
[Plex Webhooks Platform] Error: address is not available 81.150.xxx.xxx:32400

For me 32400 is the correct port I'm running Plex on, not 32401. There's nothing wrong with my network interface and it can access the external IP fine for all other apps running on the same NAS. (I have Homebridge installed using the Synology NAS app).

I think it might be a bug.
