### ISSUE TITLE
Using with multiple players. (Pinpoint only 1 player, not everything the server sends)

### ISSUE THREAD

**Issue by DoinitSideways** [iharosi/homebridge-plex-webhooks#19]
My Plex server serves multiple devices. Id like to narrow down the playing of media to just one player, a NUC running plex embedded.

I would like to be able to select an individual player IP/uuid to listen to. (Or other with multiple players in there homes could have multiple sensors)

Ive looked at this (https://support.plex.tv/articles/115002267687-webhooks/) which talks about listening to an individual player, but i just do not have the technical ability to mash it together (I am a construction supervise who can build high rise buildings... i failed coding so many times when i studied my engineering and IT degree over 15 years ago)

Happy to donate for your time and assistance...

**Comment by iharosi** [comment]
If you're using Homebridge on your NUC, there you can add multiple devices easily on the plugin's settings panel.
You can use the `Player.uuid` for the path-value pair fields.
