### ISSUE TITLE
Can't create more than one accessory

### ISSUE THREAD

**Issue by moviemakr1620** [iharosi/homebridge-plex-webhooks#2]
I installed your plugin and had it working but when i went to add more accessories only the first one would activate when playing on plex.  the rest would show up but not activate until i brought them to the top. This is my config code.  I changed the different ports because it didn't run with only one and added all three in plex.
```
"accessories": [
    {
        "accessory": "PlexWebhooksServer",
        "name": "Plex Family Room",
        "port": "32401",
        "filter": [
            {
                "Account.title": "Jason Clee",
                "Player.title": "Family room"
            }
        ]
    },
    {
        "accessory": "PlexWebhooksServer",
        "name": "Plex Living Room",
        "port": "32402",
        "filter": [
            {
                "Account.title": "Jason Clee",
                "Player.title": "Living Room"
            }
        ]
    },
    {
        "accessory": "PlexWebhooksServer",
        "name": "Plex Theater",
        "port": "32403",
        "filter": [
            {
                "Account.title": "Jason Clee",
                "Player.title": "Theater"
            }
        ]
    }
],
```

**Comment by iharosi** [comment]
Hi @moviemakr1620,
Thanks for reporting, I'll take a look and get back to you.

**Comment by iharosi** [comment]
Hi @moviemakr1620,

Version 1.1.1 has been released to NPM. It will fix the issue.
Thanks for reporting this bug!

**Comment by moviemakr1620** [comment]
Thanks so much for responding so quickly!  Didn’t know if I was just not doing something right.

Jason Clee
(484) 459-3782
moviemakr1620@gmail.com <mailto:moviemakr1620@gmail.com>
www.jasonshawnclee.com <http://www.jasonshawnclee.com/>

**Comment by clemons92** [comment]
I'm running v.1.1.1 of the plugin, however I'm experiencing this same issue! I would post my config file, but it looks the same as OPs. Any suggestions for me?

**Comment by iharosi** [comment]
Hi!
I really need to see your config before I can say anything. Could you please share yours?

**Comment by clemons92** [comment]
> Hi!
> I really need to see your config before I can say anything. Could you please share yours?

Absolutely, just updated my comment to include config file
