### ISSUE TITLE
Add a "NOT" for the Value Pairs

### ISSUE THREAD

**Issue by GitPuffy** [iharosi/homebridge-plex-webhooks#22]
I'd like to be able to add a NOT to the value pair.   For example activate the sensor when anyone BUT a certain user is playing content from the Plex server.

I tried prefacing my user information with a "!" but that did not work.

Thank you.

**Comment by SmolSoftBoi** [comment]
I can help with this. What help do you require?

**Comment by iharosi** [comment]
Feel free to send a pull request with the changes.

**Comment by iharosi** [comment]
Thanks for the contribution @SmolSoftBoi! 🙌
