### ISSUE TITLE
Plugin turns lights off for any plex instance instead of what rules I set

### ISSUE THREAD

**Issue by abhiiously** [iharosi/homebridge-plex-webhooks#25]
My config is below. Any time anyone on my plex server starts a movie, it turns off my lights. I want to make sure it only does it for myself and on a specific plex device. Specifically my apple tv. For some reason if I watch it from plex on my PC it still shuts my lights off. 

Here is the code
https://pastebin.com/44AQrrrN

**Comment by iharosi** [comment]
Please fill out the ticket with details of your environment software versions etc. to have a better understanding of the issue. Also, please avoid linking configs from outside. Thanks
