### ISSUE TITLE
Issue with multiple sensors

### ISSUE THREAD

**Issue by clemons92** [iharosi/homebridge-plex-webhooks#4]
Hello there,

I'm running v.1.1.1 of the plugin, however I'm experiencing an issue where the second sensor's ruleset never gets checked, so only the first Sensor works. Any tips or tricks to get this working would be greatly appreciated on my end!

Log info:
[12/7/2020, 5:52:31 AM] [Plex Sensor - Living Room] Checking the 1st ruleset:
[12/7/2020, 5:52:31 AM] [Plex Sensor - Living Room] + Looking for "[my email here]" at "Account.title", found "[my email here]".
[12/7/2020, 5:52:31 AM] [Plex Sensor - Living Room] + Looking for "Media Server" at "Server.title", found "Media Server".
[12/7/2020, 5:52:31 AM] [Plex Sensor - Living Room] - Looking for "Living Room" at "Player.title", found "Great Room".

Accessory #1 named: Plex Sensor - Living Room, works fine.
Accessory #2 named: Plex Sensor - Great Room and is never triggered, its seems as though the first sensor is the only one being validated.. the second sensor never gets the opportunity to check the ruleset and is not outputted in the log. The first accessory is the only one being validated.

Here's my config:
```
"accessories": [
        {
            "accessory": "PlexWebhooksServer",
            "name": "Plex Sensor - Living Room",
            "plex_token": "[my token here]",
            "port": "32401",
            "filter": [
                {
                    "Account.title": "[my email here]",
                    "Server.title": "Media Server",
                    "Player.title": "Living Room",
                    "Player.uuid": "[Device UUID]"
                }
            ]
        },
        {
            "accessory": "PlexWebhooksServer",
            "name": "Plex Sensor - Great Room",
            "plex_token": "[my token here]",
            "port": "32402",
            "filter": [
                {
                    "Account.title": "[my email here]",
                    "Server.title": "Media Server",
                    "Player.title": "Great Room",
                    "Player.uuid": "[Device UUID]"
                }
            ]
        }
    ],

**Comment by iharosi** [comment]
Hi,

Could you please share your Plex's Webhook config page? Have you added the second URL to webhooks?

**Comment by clemons92** [comment]
Ah that must be my issue, I will look for the second url in the xml and post back.

**Comment by clemons92** [comment]
Thank you very much, loving the plugin @iharosi

**Comment by iharosi** [comment]
Thanks, I'm glad to hear it! :)
