### ISSUE TITLE
Possibly a n00b Q

### ISSUE THREAD

**Issue by poiromaniax** [iharosi/homebridge-plex-webhooks#5]
Sorry if this is a n00b question, but Im not sure where I actually specify what I want to happen once the webhook triggers the server?

How do I assign devices and the action I want to happen on that specific trigger?

e.g movie.start triggers lights to turn off etc

**Comment by iharosi** [comment]
You can do all the automation in the Home app on iOS.

**Comment by poiromaniax** [comment]
Do I need to have a HomePod/Apple TV setup under the "Automation" tab? If I dont have those, it wont work?

**Comment by iharosi** [comment]
I'm not sure if a Home Hub is required for automations but here you can find more help: https://support.apple.com/en-us/HT207057

This plugin exposes an occupancy sensor in your Home app, and based on your Plex media pley state will trigger occupancy what you can use for automations in Home.

**Comment by iharosi** [comment]
In a couple of days I'll release a new 2.0.0 version of this plugin with a more user friendly configuration panel for Homebridge UI. Only a couple of minor things left and I need to update the readme file. Keep an eye on it!
